#! /usr/bin/env python3
# print charging info

import zero_server

def c2f(c):
   return (c*9/5)+32

try:
   pwpk=zero_server.read('PwPk')
except ConnectionRefusedError:
   print('server is down')
   raise SystemExit

if isinstance(pwpk, str):
   print(pwpk)
   raise SystemExit

dst3=zero_server.read('DSt3')

t=dst3['minutes_until_charged']
h, m=divmod(t, 60)
print('time remaining: %d:%02d  min temp: %.1f  max temp: %.1f  voltage: %.1f  percentage: %d' %
      (h, m, c2f(pwpk['pack_temp_min_c']), c2f(pwpk['pack_temp_max_c']),
       pwpk['pack_voltage_v'], pwpk['charge_pct']))
